services:
  db:
    image: mariadb:latest
    container_name: zluqet-db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE:     zluqet
      MARIADB_USER:         user
      MARIADB_PASSWORD:     password
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  app:
    image: ghcr.io/zluqe/zluqet:latest
    container_name: zluqet-app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      PORT:                 "5000"
      DB_TYPE:              "mariadb"
      DB_HOST:              "db"
      DB_PORT:              "3306"
      DB_NAME:              "zluqet"
      DB_USER:              "user"
      DB_PASS:              "password"
      REQUESTS_PER_MINUTE:  "5"
      CACHE_MAX:            "1000"
      MAX_LENGTH:           "25000"

volumes:
  db_data: